FROM amazoncorretto:21

# set environment variables (can be overridden at runtime)
ENV KLIP_HTTP_PORT=8080
ENV KLIP_AWS_REGION=us-west-2
ENV KLIP_S3_BUCKET=cdn.klip.com
ENV KLIP_CACHE_BUCKET=cdn.klip.com
ENV KLIP_CACHE_FOLDER=_cache/

# Create app directory and set working directory
WORKDIR /app

# Copy the JAR file built from Gradle
COPY build/libs/klip-all.jar /app/klip-all.jar

# Expose the HTTP port
EXPOSE 8080

# Start the application
CMD ["java", "-jar", "klip-all.jar"]
